# Generated by Django 3.2 on 2022-06-24 04:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_processed', 'Not Processed'), ('processed', 'Processed'), ('shipped', 'Shipping'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_processed', max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('full_name', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=255)),
                ('shipping_nombre', models.CharField(max_length=255)),
                ('shipping_tiempo', models.CharField(max_length=255)),
                ('shipping_precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_proceso', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('fecha_agregado', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='producto.producto')),
            ],
        ),
    ]
