# Generated by Django 3.2 on 2022-06-23 04:20

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('producto_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('url', models.TextField()),
                ('rango', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('fecha_creada', models.DateTimeField(default=datetime.datetime.now)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='producto.funcion')),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Productos', to='producto.material', verbose_name='material')),
            ],
        ),
    ]
